### ISSUE TITLE
Buttons

### ISSUE THREAD

**Issue by atarbig** [Marekkon5/traxsourcetagger#1]
I have main pc windows 10 pro original, tagger open but buttons "Repository" "Browse" don't work for me. I click on buton but nothing. Button "Next" ok. But on my laptop this buttons work. Where can be  problems?

**Comment by Marekkon5** [comment]
We are aware of that problem, it is fixed in master, will add as release tonight. If you dont wanna wait you can use the exe from Actions.

**Comment by bascurtiz** [comment]
@atarbig 
The hotfix is applied and released. Check it out here: https://github.com/Marekkon5/traxsourcetagger/releases/tag/0.1.0-fix

**Comment by atarbig** [comment]
Please check release again for windows 10, "exe" don't work. Maybe this file from "actions". I try on my pc and laptop, 0.1.1-fix no work now for all computers.

**Comment by bascurtiz** [comment]
So 0.1.0-fix release still has the issue of buttons not responding for you?
You should see a pop-up msg like this:
![image](https://user-images.githubusercontent.com/34075088/106367446-0a32eb80-6343-11eb-8025-9917c1dbe9ae.png)

Then hit OK, and hit Yes to make the change.
That should make the buttons work.

Let me know how that works out.

**Comment by atarbig** [comment]
i click on Traxsource Tagger.exe and this file not open (it's fix version) (for info beatport/discogs all ok)

**Comment by bascurtiz** [comment]
Have you installed Microsoft Visual C++ Redistributable from here: https://aka.ms/vs/16/release/vc_redist.x64.exe ?

**Comment by atarbig** [comment]
yes, sure. 0.1.0 open .exe file but buttons don't work. 0.1.0-fix this .exe file not open

**Comment by Marekkon5** [comment]
I added workaround, let me know if it works (binary in Actions artifact, should be ready within 10 minutes).

**Comment by atarbig** [comment]
It's work now! Thank you.

**Comment by Marekkon5** [comment]
Thank you for testing, added as release.
