### ISSUE TITLE
Crashes on windows 8.1

### ISSUE THREAD

**Issue by frankiebones2016** [Marekkon5/traxsourcetagger#3]
When opening and running as administrator it completely crashes.

**Comment by Marekkon5** [comment]
Sadly, Traxsource tagger depends on Edge, so it requires Windows 10. You'll have to update or use another OS. Sorry for the inconvenience.

**Comment by frankiebones2016** [comment]
> 
> 
> Sadly, Traxsource tagger depends on Edge, so it requires Windows 10. You'll have to update or use another OS. Sorry for the inconvenience.

Thanks for your quick reply. Can you also look into beatport tagger? I have been getting 100 percent fails every time I have searched. It was working fine a week ago.

**Comment by Marekkon5** [comment]
I already said we're working on it, and it's currently very unreliable, because Beatport is doing internal changes.
