### ISSUE TITLE
Release date field

### ISSUE THREAD

**Issue by atarbig** [Marekkon5/traxsourcetagger#4]
Hi! Release date from pre-order not write in file.
Check
Jizz - Bring It (pre-order / 2021-02-19 )
https://www.traxsource.com/search?term=Jizz+-+Bring+It

https://www.traxsource.com/search?term=Ian+O%27Donovan+-+Rath+Of+The+Synods
Pre-order for 2021-03-01

Joeski - Toque De Palo
https://www.traxsource.com/search?term=Joeski+-+Toque+De+Palo

Lauren Lo Sung - Cosmic Flow
https://www.traxsource.com/search?term=Lauren+Lo+Sung+-+Cosmic+Flow

**Comment by Marekkon5** [comment]
Hello, I made a patch. You can try it by downloading the binary from "Actions" tab. Let me know if it works.

**Comment by atarbig** [comment]
it's work now
